version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      # - IMAGE_VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "$REPOSITORY_URI:$IMAGE_VERSION"
      - docker build -t $REPOSITORY_URI:${IMAGE_NAME:-image}-$IMAGE_VERSION -f docker/node-app.prod.dockerfile .
      # - docker tag $REPOSITORY_URI:${IMAGE_NAME:-image}-$IMAGE_VERSION $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:${IMAGE_NAME:-image}-$IMAGE_VERSION
